meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: nrpe
    templates:
      - { release: nrpe, name: nrpe }
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set nrpe networks" ))
    properties:
      nrpe:
        checks:
          nrpe-log: check_log -F /var/vcap/sys/log/nrpe/nrpe.log -O /tmp/nrpe.log -q ERROR
          cpu:      check_cpu
          mem:      check_mem -w 20 -c 10

networks: (( param "please set networks" ))

properties: {}
